version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crown_back_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate && bundle exec rails s -p 3000"
    volumes:
      - .:/backend/crown
    ports:
      - "3000:3000"
    depends_on:
      - db
